server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.131:3306/quartz?userUnicode=true&charactorEncoding=utf-8&userSSl=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      maximum-pool-size: 10
      read-only: false
mybatis-plus:
  type-aliases-package: com.lin.quartz.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mappers/*.xml
